name: ALL rig Deployment

on:
  push:
    branches:
      - all-rig-0.1-lesson-progress

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: all-dev-rig

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install AWS CLI
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y awscli
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
      - name: Build and Package Application
        run: |
          npm install
      
      - name: Build Production
        run: npm run build
      - name: Deploy to S3 Bucket
        run: |
          aws s3 sync ./build s3://sballappliance/assets/sb-ai/
      - name: Debug Environment Variables
        run: |
          echo "REACT_APP_AWS_S3_BUCKET_NAME: ${{REACT_APP_AWS_S3_BUCKET_NAME}}"
          echo "AWS_REGION: $AWS_REGION"
          echo "secrate": ${{secrets.REACT_APP_AWS_S3_BUCKET_NAME}}
       ### Invalidate Cloudfront
      - name: Cloudfront Invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
